name: primer-ejemplo
on:
  push:
    branches:
      - react_app_deploy
jobs:
  Build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: npm install && npm run build
      - name: Upload-Artifact
        uses: actions/upload-artifact@v2
        with:
          name: carpeta
          path: build/

  Deploy-job:
    runs-on: ubuntu-latest
    needs: Build-job
    steps:
      - name: Upload-Artifact
        uses: actions/download-artifact@v2
        with:
          name: carpeta
      - name: Deploy to surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'deploysurgesalva.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
