name: primer-ejemplo
on:
  push:
    branches:
      - nodejs_jest_job
      - nodejs_linter_job
      - nodejs_nodeversions_job
      - nodejs_environment_job
      - nodejs_send_email
jobs:
  # linter-execution:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node: [10, 12]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Setting node version
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node }}
  #     - name: Linter execution
  #       uses: github/super-linter@v4
  #       env:
  #         DEFAULT_BRANCH: nodejs_linter_job
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         LINTER_RULES_PATH: /
  #         JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
  #         VALIDATE_JAVASCRIPT_ES: true

  test-execution:
    runs-on: ubuntu-latest
    # needs: linter-execution
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        id: test
        run: npm install jest && npm test
        continue-on-error: true
      - name: Print error
        if: steps.test.outcome != 'success'
        run: echo "El test ha fallado"

      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     to: salroiba03@gmail.com
      #     from: Salva
      #     subject: Github Actions job result
      #     body: Mensaje enviado

  environment_test_execution:
    runs-on: ubuntu-latest
    # needs: linter-execution
    steps:
      - name: Checkout code
        id: Hola
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: "Pepe"
